export const results = {
    rankings : [
            {
            "id":981036,
            "first_name":"Daniil",
            "last_name":"Medvedev",
            "full_name":"Daniil Medvedev",
            "country":"Russia",
            "ranking":1,
            "movement":"",
            "ranking_points":8160,
            },
            {
            "id":342990,
            "first_name":"Alexander",
            "last_name":"Zverev",
            "full_name":"Alexander Zverev",
            "country":"Germany",
            "ranking":2,
            "movement":"",
            "ranking_points":7030,
            },
            {
            "id":89304,
            "first_name":"Novak",
            "last_name":"Djokovic",
            "full_name":"Novak Djokovic",
            "country":"Serbia",
            "ranking":3,
            "movement":"",
            "ranking_points":6770,
            },
            {
            "id":86928,
            "first_name":"Rafael",
            "last_name":"Nadal",
            "full_name":"Rafael Nadal",
            "country":"Spain",
            "ranking":4,
            "movement":"",
            "ranking_points":6525,
            },
            {
            "id":715500,
            "first_name":"Casper",
            "last_name":"Ruud",
            "full_name":"Casper Ruud",
            "country":"Norway",
            "ranking":5,
            "movement":"",
            "ranking_points":5050,
            },
            {
            "id":734208,
            "first_name":"Stefanos",
            "last_name":"Tsitsipas",
            "full_name":"Stefanos Tsitsipas",
            "country":"Greece",
            "ranking":6,
            "movement":"",
            "ranking_points":4945,
            },
            {
            "id":1655550,
            "first_name":"Carlos",
            "last_name":"Alcaraz",
            "full_name":"Carlos Alcaraz",
            "country":"Spain",
            "ranking":7,
            "movement":"",
            "ranking_points":4893,
            },
            {
            "id":640542,
            "first_name":"Andrey",
            "last_name":"Rublev",
            "full_name":"Andrey Rublev",
            "country":"Russia",
            "ranking":8,
            "movement":"",
            "ranking_points":3870,
            },
            {
            "id":1152090,
            "first_name":"Aliassime",
            "last_name":"Auger",
            "full_name":"Aliassime Auger",
            "country":"Canada",
            "ranking":9,
            "movement":"",
            "ranking_points":3760,
            },
            {
            "id":953388,
            "first_name":"Hubert",
            "last_name":"Hurkacz",
            "full_name":"Hubert Hurkacz",
            "country":"Poland",
            "ranking":10,
            "movement":"+2",
            "ranking_points":3738,
            },
            {
            "id":676710,
            "first_name":"Matteo",
            "last_name":"Berrettini",
            "full_name":"Matteo Berrettini",
            "country":"Italy",
            "ranking":11,
            "movement":"-1",
            "ranking_points":3480,
            }
    ]
        
    
}