export const results = {
    rankings : [
            {
            "id":1369644,
            "first_name":"Iga",
            "last_name":"Swiatek",
            "full_name":"Iga Swiatek",
            "country":"Poland",
            "ranking":1,
            "movement":"",
            "ranking_points":8576,
            },
            {
            "id":296124,
            "first_name":"Ashleigh",
            "last_name":"Barty",
            "full_name":"Ashleigh Barty",
            "country":"Australia",
            "ranking":1,
            "movement":"",
            "ranking_points":7980,
            },
            {
            "id":332418,
            "first_name":"Ons",
            "last_name":"Jabeur",
            "full_name":"Ons Jabeur",
            "country":"Tunisia",
            "ranking":2,
            "movement":"+1",
            "ranking_points":4340,
            },
            {
            "id":288066,
            "first_name":"Anett",
            "last_name":"Kontaveit",
            "full_name":"Anett Kontaveit",
            "country":"Estonia",
            "ranking":3,
            "movement":"-1",
            "ranking_points":4306,
            },
            {
            "id":414312,
            "first_name":"Paula",
            "last_name":"Badosa",
            "full_name":"Paula Badosa",
            "country":"Spain",
            "ranking":4,
            "movement":"",
            "ranking_points":4245,
            },
            {
            "id":395712,
            "first_name":"Maria",
            "last_name":"Sakkari",
            "full_name":"Maria Sakkari",
            "country":"Greece",
            "ranking":5,
            "movement":"",
            "ranking_points":4205,
            },
            {
            "id":946536,
            "first_name":"Aryna",
            "last_name":"Sabalenka",
            "full_name":"Aryna Sabalenka",
            "country":"Belarus",
            "ranking":6,
            "movement":"",
            "ranking_points":4046,
            },
            {
            "id":124404,
            "first_name":"Karolina",
            "last_name":"Pliskova",
            "full_name":"Karolina Pliskova",
            "country":"Czech Republic",
            "ranking":7,
            "movement":"",
            "ranking_points":3777,
            },
            {
            "id":351102,
            "first_name":"Danielle",
            "last_name":"Collins",
            "full_name":"Danielle Collins",
            "country":"USA",
            "ranking":8,
            "movement":"",
            "ranking_points":3255,
            },
            {
            "id":269016,
            "first_name":"Jessica",
            "last_name":"Pegula",
            "full_name":"Jessica Pegula",
            "country":"USA",
            "ranking":9,
            "movement":"",
            "ranking_points":3156,
            },
            {
            "id":304668,
            "first_name":"Garbine",
            "last_name":"Muguruza",
            "full_name":"Garbine Muguruza",
            "country":"Spain",
            "ranking":10,
            "movement":"",
            "ranking_points":3015,
            }
    ]
}